In [12]:
import pandas as pd

# Wczytanie oczyszczonego pliku Excela
df = pd.read_excel("oczyszczone_dane_lotniska.xlsx")

# Wyświetlenie podstawowych informacji
print("➡️ Liczba wierszy i kolumn:", df.shape)

print("\n➡️ Pierwsze 5 wierszy danych:")
display(df.head())

# Sprawdzenie braków danych
print("\n➡️ Liczba braków danych w każdej kolumnie:")
print(df.isnull().sum())

# Typy danych
print("\n➡️ Typy danych:")
print(df.dtypes)

# Podstawowe statystyki opisowe (zachowane tylko do wyświetlenia)
print("\n➡️ Statystyki opisowe dla zmiennych liczbowych:")
display(df.select_dtypes(include='number').describe().T.round(2))

➡️ Liczba wierszy i kolumn: (110, 19)

➡️ Pierwsze 5 wierszy danych:

,kraj,lotnisko,rok,pax,lotniska_300km,flota_komercyjna,pasy_startowe,bramki,odprawy,autostrady_km,kolej_elektr_km,ofiary_lotnicze,turystyka,dostep_morze_kraj,dostep_morze_miasto,lotniska_kraj,pkb_pps,pkb_realny,powierzchnia_km2
0,FRANCJA,PARIS-CHARLES DE GAULLE airport,2013,61889855,1,571,4.0,180.0,420.0,11552,53739.875,0,38480199,TAK,NIE,NaN,109,34990,551695
1,FRANCJA,PARIS-CHARLES DE GAULLE airport,2014,63648567,1,561,4.0,180.0,420.0,11560.142,52002.002,2,38229887,TAK,NIE,43.0,108,35150,551695
2,FRANCJA,PARIS-CHARLES DE GAULLE airport,2015,65674223,1,553,4.0,180.0,420.0,11598.82,51074.944,150,28689286,TAK,NIE,42.0,106,35370,551695
3,FRANCJA,PARIS-CHARLES DE GAULLE airport,2016,65859946,1,550,4.0,180.0,420.0,11612.453,50291.348,0,38049563,TAK,NIE,44.0,105,35540,551695
4,FRANCJA,PARIS-CHARLES DE GAULLE airport,2017,69418254,1,555,NaN,NaN,NaN,11618.101.,50946.371,0,38695712,TAK,NIE,44.0,103,36140,551695

➡️ Liczba braków danych w każdej kolumnie:
kraj                    0
lotnisko                0
rok                     0
pax                     0
lotniska_300km          0
flota_komercyjna        0
pasy_startowe          24
bramki                 37
odprawy                28
autostrady_km           1
kolej_elektr_km         0
ofiary_lotnicze         0
turystyka               0
dostep_morze_kraj       0
dostep_morze_miasto     0
lotniska_kraj          10
pkb_pps                 0
pkb_realny              0
powierzchnia_km2        0
dtype: int64

➡️ Typy danych:
kraj                    object
lotnisko                object
rok                      int64
pax                      int64
lotniska_300km           int64
flota_komercyjna         int64
pasy_startowe          float64
bramki                 float64
odprawy                float64
autostrady_km           object
kolej_elektr_km        float64
ofiary_lotnicze          int64
turystyka                int64
dostep_morze_kraj       object
dostep_morze_miasto     object
lotniska_kraj          float64
pkb_pps                  int64
pkb_realny               int64
powierzchnia_km2         int64
dtype: object

➡️ Statystyki opisowe dla zmiennych liczbowych:

,count,mean,std,min,25%,50%,75%,max
rok,110.0,2018.00,3.18,2013.0,2015.00,2018.00,2021.00,2023.00
pax,110.0,39495238.58,17900411.87,7262330.0,26934696.00,38971216.50,52525279.00,76136816.00
lotniska_300km,110.0,2.60,1.50,0.0,1.00,3.00,4.00,5.00
flota_komercyjna,110.0,545.21,296.49,181.0,281.00,499.00,570.00,1135.00
pasy_startowe,86.0,3.14,1.28,1.0,2.00,3.00,4.00,6.00
bramki,73.0,143.01,60.21,0.0,83.00,147.00,192.00,238.00
odprawy,82.0,344.51,122.54,0.0,259.50,337.50,452.00,502.00
kolej_elektr_km,110.0,30946.94,24820.75,2426.0,5185.25,22669.37,50782.62,70741.06
ofiary_lotnicze,110.0,3.47,20.14,0.0,0.00,0.00,0.00,150.00
turystyka,110.0,26925353.87,17341352.20,2396689.0,11911938.25,25623541.00,40133709.50,54875841.00
lotniska_kraj,100.0,23.24,13.17,3.0,7.00,25.50,32.25,44.00
pkb_pps,110.0,123.60,118.81,73.0,91.00,104.00,126.00,1312.00
pkb_realny,110.0,37454.45,14386.33,18330.0,26770.00,36140.00,42982.50,92820.00
powierzchnia_km2,110.0,333699.70,193100.36,41865.0,92152.00,357592.00,506030.00,551695.00